# coding: utf-8

"""
    Container Registry service

    ## Overview Container Registry service enables IONOS clients to manage docker and OCI compliant registries for use by their managed Kubernetes clusters. Use a Container Registry to ensure you have a privately accessed registry to efficiently support image pulls. ## Changelog ### 1.1.0  - Added new endpoints for Repositories  - Added new endpoints for Artifacts  - Added new endpoints for Vulnerabilities  - Added registry vulnerabilityScanning feature ### 1.2.0  - Added registry `apiSubnetAllowList` ### 1.2.1  - Amended `apiSubnetAllowList` Regex 

    The version of the OpenAPI document: 1.2.1
    Contact: support@cloud.ionos.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from ionoscloud_container_registry.models.registry_features import RegistryFeatures
from ionoscloud_container_registry.models.storage_usage import StorageUsage
from ionoscloud_container_registry.models.weekly_schedule import WeeklySchedule
from typing import Optional, Set
from typing_extensions import Self

class RegistryProperties(BaseModel):
    """
    RegistryProperties
    """ # noqa: E501
    garbage_collection_schedule: Optional[WeeklySchedule] = Field(default=None, alias="garbageCollectionSchedule")
    hostname: Optional[StrictStr] = None
    location: Optional[StrictStr] = None
    name: Optional[Annotated[str, Field(strict=True)]] = None
    storage_usage: Optional[StorageUsage] = Field(default=None, alias="storageUsage")
    features: Optional[RegistryFeatures] = None
    api_subnet_allow_list: Optional[Annotated[List[Annotated[str, Field(strict=True)]], Field(min_length=0, max_length=25)]] = Field(default=None, description="Subnets and IPs that are allowed to access the registry API, supports IPv4 and IPv6. Maximum of 25 items may be specified. If no CIDR is given /32 and /128 are assumed for IPv4 and IPv6 respectively. 0.0.0.0/0 can be used to deny all traffic. __Note__: If this list is empty or not set, there are no restrictions. ", alias="apiSubnetAllowList")
    __properties: ClassVar[List[str]] = ["garbageCollectionSchedule", "hostname", "location", "name", "storageUsage", "features", "apiSubnetAllowList"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RegistryProperties from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of garbage_collection_schedule
        if self.garbage_collection_schedule:
            _dict['garbageCollectionSchedule'] = self.garbage_collection_schedule.to_dict()
        # override the default output from pydantic by calling `to_dict()` of storage_usage
        if self.storage_usage:
            _dict['storageUsage'] = self.storage_usage.to_dict()
        # override the default output from pydantic by calling `to_dict()` of features
        if self.features:
            _dict['features'] = self.features.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RegistryProperties from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "garbageCollectionSchedule": WeeklySchedule.from_dict(obj["garbageCollectionSchedule"]) if obj.get("garbageCollectionSchedule") is not None else None,
            "hostname": obj.get("hostname"),
            "location": obj.get("location"),
            "name": obj.get("name"),
            "storageUsage": StorageUsage.from_dict(obj["storageUsage"]) if obj.get("storageUsage") is not None else None,
            "features": RegistryFeatures.from_dict(obj["features"]) if obj.get("features") is not None else None,
            "apiSubnetAllowList": obj.get("apiSubnetAllowList")
        })
        return _obj


