# coding: utf-8

"""
    Container Registry service

    ## Overview Container Registry service enables IONOS clients to manage docker and OCI compliant registries for use by their managed Kubernetes clusters. Use a Container Registry to ensure you have a privately accessed registry to efficiently support image pulls. ## Changelog ### 1.1.0  - Added new endpoints for Repositories  - Added new endpoints for Artifacts  - Added new endpoints for Vulnerabilities  - Added registry vulnerabilityScanning feature ### 1.2.0  - Added registry `apiSubnetAllowList` ### 1.2.1  - Amended `apiSubnetAllowList` Regex 

    The version of the OpenAPI document: 1.2.1
    Contact: support@cloud.ionos.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class RepositoryMetadata(BaseModel):
    """
    RepositoryMetadata
    """ # noqa: E501
    created_date: Optional[datetime] = Field(default=None, description="The ISO 8601 creation timestamp.", alias="createdDate")
    created_by: Optional[StrictStr] = Field(default=None, description="Unique name of the identity that created the resource.", alias="createdBy")
    created_by_user_id: Optional[StrictStr] = Field(default=None, description="Unique id of the identity that created the resource.", alias="createdByUserId")
    last_modified_date: Optional[datetime] = Field(default=None, description="The ISO 8601 modified timestamp.", alias="lastModifiedDate")
    last_modified_by: Optional[StrictStr] = Field(default=None, description="Unique name of the identity that last modified the resource.", alias="lastModifiedBy")
    last_modified_by_user_id: Optional[StrictStr] = Field(default=None, description="Unique id of the identity that last modified the resource.", alias="lastModifiedByUserId")
    resource_urn: Optional[StrictStr] = Field(default=None, description="Unique name of the resource.", alias="resourceURN")
    artifact_count: Optional[StrictInt] = Field(default=None, alias="artifactCount")
    pull_count: Optional[StrictInt] = Field(default=None, alias="pullCount")
    push_count: Optional[StrictInt] = Field(default=None, alias="pushCount")
    last_pulled_at: Optional[datetime] = Field(default=None, alias="lastPulledAt")
    last_pushed_at: Optional[datetime] = Field(default=None, alias="lastPushedAt")
    last_severity: Optional[StrictStr] = Field(default=None, description="The maximum vulnerability severity of the artifact last pushed in the repository, if any", alias="lastSeverity")
    __properties: ClassVar[List[str]] = ["createdDate", "createdBy", "createdByUserId", "lastModifiedDate", "lastModifiedBy", "lastModifiedByUserId", "resourceURN", "artifactCount", "pullCount", "pushCount", "lastPulledAt", "lastPushedAt", "lastSeverity"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RepositoryMetadata from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RepositoryMetadata from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "createdDate": obj.get("createdDate"),
            "createdBy": obj.get("createdBy"),
            "createdByUserId": obj.get("createdByUserId"),
            "lastModifiedDate": obj.get("lastModifiedDate"),
            "lastModifiedBy": obj.get("lastModifiedBy"),
            "lastModifiedByUserId": obj.get("lastModifiedByUserId"),
            "resourceURN": obj.get("resourceURN"),
            "artifactCount": obj.get("artifactCount"),
            "pullCount": obj.get("pullCount"),
            "pushCount": obj.get("pushCount"),
            "lastPulledAt": obj.get("lastPulledAt"),
            "lastPushedAt": obj.get("lastPushedAt"),
            "lastSeverity": obj.get("lastSeverity")
        })
        return _obj


